name: Deploy to Amazon ECS

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-ecr-image:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.SERVER_ENV_PROD }}" > .env
          cat .env
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          IMAGE_TAG_APP: ${{ secrets.VERSION_TAG_API }}
          IMAGE_TAG_WORKER: ${{ secrets.VERSION_TAG_WORKER }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_APP -f Dockerfile .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_WORKER -f worker.Dockerfile .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_APP
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_WORKER
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_APP"
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG_WORKER"

  Continuous-Deployment:
     needs: build-and-push-ecr-image
     runs-on: [aws-deedsign]
     steps:      
       - name: Check current user
         run: |
           if [ "$(whoami)" = "ubuntu" ]; then
              echo "User is ubuntu"
              sudo su
           else
              echo "User is not ubuntu"
           fi
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: ${{ secrets.AWS_REGION }}
   
       - name: Change the directory and Deploy the application
         run: |
           cd ${{ secrets.AWS_DIRECTORY }}
           aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}
           docker-compose down
           docker-compose pull
           echo "Deleting /sites/your folder/api folder..."
           sudo rm -rf /sites/your folder/api
           docker run -it -d --name app-api ${{ secrets.ECR_IMAGES }}
           sudo docker cp app-api:/var/www/app/ api
           sudo chown -R www-data:www-data /sites/deedsign-app/api
           docker rm -f app-api
           docker-compose up -d
       - name: final Stage
         run: |
           cd ${{ secrets.AWS_DIRECTORY }}
           sudo ./deploy-api.sh

